version: "3.7"

services:
  poc:
    hostname: poc
    container_name: poc
    build:
      context: ./poc
      dockerfile: Dockerfile
    tty: true
    networks:
      default:
        ipv4_address: 192.168.2.50
    volumes:
      - type: bind
        source: ./poc/request_test.sh
        target: /request_test.sh

  nginx001:
    hostname: poc-proxy.exmaple.com
    container_name: poc-proxy.exmaple.com
    build:
      context: ./proxy
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./proxy/config/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./proxy/config/default.conf
        target: /etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - 8080:80
      - 8081:443
    networks:
      default:
        ipv4_address: 192.168.2.200

  webapp001:
    hostname: webapp001
    container_name: webapp001
    domainname: poc.example.com
    user: root
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./webapp/main.py
        target: /var/www/main.py
      - type: bind
        source: ./webapp/templates
        target: /var/www/templates
    dns:
      - 8.8.8.8
      - 9.9.9.9
    tty: true
    environment:
      TZ: "Asia/Tokyo"
    networks:
      default:
        ipv4_address: 192.168.2.100
  webapp002:
    hostname: webapp002
    container_name: webapp002
    domainname: poc.example.com
    user: root
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./webapp/main.py
        target: /var/www/main.py
      - type: bind
        source: ./webapp/templates
        target: /var/www/templates
    dns:
      - 8.8.8.8
      - 9.9.9.9
    tty: true
    environment:
      TZ: "Asia/Tokyo"
    networks:
      default:
        ipv4_address: 192.168.2.101
  webapp003:
    hostname: webapp003
    container_name: webapp003
    domainname: poc.example.com
    user: root
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./webapp/main.py
        target: /var/www/main.py
      - type: bind
        source: ./webapp/templates
        target: /var/www/templates
    dns:
      - 8.8.8.8
      - 9.9.9.9
    tty: true
    environment:
      TZ: "Asia/Tokyo"
    networks:
      default:
        ipv4_address: 192.168.2.102

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.2.0/24
