# Licensed to this repo under one or more contributor license agreements.
# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership. this repo licenses this file to you under
# the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License.

---

version: "3.7"

x-web-template: &template
  domainname: poc.example.com
  user: root
  build:
    context: ./webapp
    dockerfile: Dockerfile
  dns:
    - 8.8.8.8
    - 9.9.9.9
  tty: true
  environment:
    TZ: "Asia/Tokyo"
  logging:
    driver: "json-file"
  stop_signal: SIGSTOP

x-web-volumes: &volumes
  volumes:
    - type: bind
      source: ./webapp/main.py
      target: /var/www/main.py
    - type: bind
      source: ./webapp/templates
      target: /var/www/templates
    - type: bind
      source: ./webapp/static
      target: /var/www/static

services:
  poc:
    hostname: poc
    container_name: poc
    build:
      context: ./poc
      dockerfile: Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./poc/request_test.sh
        target: /request_test.sh
    extra_hosts:
      - "ib.dev.com:192.168.2.100"

  offload:
    hostname: nginx.dev.com
    container_name: nginx.dev.com
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./nginx/config/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/config/ssl_offload.nginxconf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./nginx/html
        target: /usr/share/nginx/html
    tty: true
    sysctls:
      net.core.somaxconn: 4
      net.ipv4.ip_local_port_range: "65533 65535"
    ports:
      - 8080:80/tcp
      - 8081:443/tcp
    networks:
      default:
        ipv4_address: 192.168.2.100

  redis:
    hostname: redis001
    container_name: redis001
    image: redis:latest
    ports:
      - 6379:6379/tcp
    command: redis-server --appendonly yes

  webapp001:
    <<: *template
    <<: *volumes
    hostname: webapp001
    container_name: webapp001
  webapp002:
    <<: *template
    <<: *volumes
    hostname: webapp002
    container_name: webapp002
  webapp003:
    <<: *template
    <<: *volumes
    hostname: webapp003
    container_name: webapp003

  webapp004:
    <<: *volumes
    hostname: webapp004
    container_name: webapp004
    build:
      context: ./webapp
      dockerfile: Dockerfile-socket
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.2.0/24
