version: "3.7"

services:
  webapp001:
    hostname: poc-webapp-001
    container_name: poc-webapp-001
    domainname: poc.example.com
    user: root
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./webapp/main.py
        target: /var/www/main.py
    dns:
      - 8.8.8.8
      - 9.9.9.9
    tty: true
  nginx001:
    hostname: poc-nginx-001
    container_name: poc-nginx-001
    build:
      context: ./rev_proxy
      dockerfile: Dockerfile
