version: 2.1

executors:
  def-ubuntu:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    shell: "/bin/bash"
    working_directory: /tmp/app

jobs:
  docker_env_info:
    executor:
      name: def-ubuntu
    steps:
      - checkout
      - run:
          name: "docker_env_info"
          command: |
            bash script/print_info.sh

  dockerfile_lint:
    executor:
      name: def-ubuntu
    steps:
      - checkout
      - run:
          name: "Dockerfile lint"
          command: |
            sudo apt apdate && apt upgrade
            sudo apt install -y jq curl wget
            docker run --rm -i hadolint/hadolint hadolint --version
      - run:
          name: "Dockerfile nginx"
          command: |
            docker run --rm -i hadolint/hadolint hadolint - --format json < nginx/Dockerfile | jq . || echo 0
      - run:
          name: "Dockerfile webapp"
          command: |
            docker run --rm -i hadolint/hadolint hadolint - --format json < webapp/Dockerfile | jq . || echo 0

  docker_image_build:
    executor:
      name: def-ubuntu
    steps:
      - checkout

workflows:
  poc_workflow:
    jobs:
      - docker_env_info
      - dockerfile_lint:
          requires:
            - docker_env_info
      - docker_image_build:
          requires:
            - docker_env_info
            - dockerfile_lint
