version: 2.1

commands:
  install_docker_compose:
    description: "Install docker-compose"
    steps:
      - run:
          name: "Install docker-compose"
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
            docker-compose version

executors:
  def-ubuntu:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    shell: "/bin/bash"
    working_directory: /tmp/app

jobs:
  docker_env_info:
    executor:
      name: def-ubuntu
    steps:
      - checkout
      - run:
          name: "docker_env_info"
          command: |
            bash script/print_info.sh

  dockerfile_lint:
    executor:
      name: def-ubuntu
    steps:
      - checkout
      - run:
          name: "Dockerfile lint"
          command: |
            sudo apt apdate && apt upgrade
            sudo apt install -y jq curl wget
            docker run --rm -i hadolint/hadolint hadolint --version
      - run:
          name: "Dockerfile nginx"
          command: |
            docker run --rm -i hadolint/hadolint hadolint - --format json < nginx/Dockerfile | jq . || echo 0
      - run:
          name: "Dockerfile webapp"
          command: |
            docker run --rm -i hadolint/hadolint hadolint - --format json < webapp/Dockerfile | jq . || echo 0

  docker_image_build:
    executor:
      name: def-ubuntu
    steps:
      - checkout
      - install_docker_compose
      - run:
          name: "docker image build"
          command: |
            export DOCKER_BUILDKIT=1
            export COMPOSE_DOCKER_CLI_BUILD=1
            time docker-compose up -d
      - run:
          name: "docker image list"
          command: |
            docker-compose ps
            docker image ls

workflows:
  poc_workflow:
    jobs:
      - docker_env_info
      - dockerfile_lint:
          requires:
            - docker_env_info
      - docker_image_build:
          requires:
            - docker_env_info
            - dockerfile_lint
